# Generated by Django 4.2.7 on 2023-12-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopEase', '0002_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./ShopEase/static/ShopEase/product_images/'),
        ),
    ]
